#!/usr/bin/env python3
"""
TikTok API Setup Helper
Helps configure and test TikTok API credentials for the bot
"""

import os
from pathlib import Path
from dotenv import load_dotenv, set_key

load_dotenv()


def get_tiktok_credentials():
    """Interactive setup for TikTok API credentials"""
    print("=" * 70)
    print("🎬 TikTok API Setup Helper")
    print("=" * 70)
    print()
    print("This helper will configure your bot to post REAL hearts to TikTok.")
    print()
    print("STEP 1: Get your TikTok API credentials")
    print("  1. Go to: https://developers.tiktok.com/")
    print("  2. Sign in with your TikTok account")
    print("  3. Create a new application")
    print("  4. Copy your Client Key and Client Secret")
    print()
    print("=" * 70)
    print()
    
    # Get Client Key
    while True:
        client_key = input("Enter your TikTok Client Key: ").strip()
        if client_key and len(client_key) > 10:
            break
        print("  ✗ Invalid Client Key. Try again.")
    
    # Get Client Secret
    while True:
        client_secret = input("Enter your TikTok Client Secret: ").strip()
        if client_secret and len(client_secret) > 10:
            break
        print("  ✗ Invalid Client Secret. Try again.")
    
    # Get Access Token (optional - can set later via OAuth)
    access_token = input("Enter your Access Token (or press Enter to skip): ").strip()
    
    print()
    print("=" * 70)
    print("STEP 2: Save credentials to .env file")
    print("=" * 70)
    
    # Find .env file location
    env_file = Path(".env")
    if not env_file.exists():
        env_file = Path(__file__).parent.parent / ".env"
    
    print(f"Saving to: {env_file.absolute()}")
    print()
    
    # Save credentials
    try:
        set_key(env_file, "TIKTOK_CLIENT_KEY", client_key)
        set_key(env_file, "TIKTOK_CLIENT_SECRET", client_secret)
        if access_token:
            set_key(env_file, "TIKTOK_ACCESS_TOKEN", access_token)
        
        print("✓ Credentials saved successfully!")
        print()
        print("=" * 70)
        print("STEP 3: Authenticate with TikTok OAuth")
        print("=" * 70)
        print()
        
        if not access_token:
            print("You need an Access Token to post hearts.")
            print()
            print("Option A: Use OAuth Flow (Recommended)")
            print("  Run: python tiktok_oauth_flow.py")
            print()
            print("Option B: Manual OAuth")
            print("  1. Visit the OAuth URL generated by the bot")
            print("  2. Authorize the bot to access your account")
            print("  3. Copy the authorization code")
            print("  4. Paste it back into the bot")
            print()
        else:
            print("✓ Access token provided!")
            print("✓ Your bot is ready to post hearts to TikTok!")
            print()
        
        return True
        
    except Exception as e:
        print(f"✗ Failed to save credentials: {e}")
        print("  Make sure you have write permissions to the directory")
        return False


def test_api_connection():
    """Test if the TikTok API connection works"""
    print()
    print("=" * 70)
    print("Testing TikTok API Connection")
    print("=" * 70)
    print()
    
    try:
        from src.tiktok_api import TikTokAPI
        
        api = TikTokAPI()
        
        # Check credentials
        if not api.client_key or not api.client_secret:
            print("✗ API credentials not configured")
            print("  Run: python tiktok_setup.py")
            return False
        
        print(f"✓ Client Key: {api.client_key[:20]}...")
        print(f"✓ Client Secret: {api.client_secret[:20]}...")
        
        if api.access_token:
            print(f"✓ Access Token: {api.access_token[:20]}...")
            
            # Try to get user info
            user_info = api.get_user_info()
            if user_info.get("data"):
                print("✓ Successfully authenticated!")
                print(f"✓ User: {user_info['data'].get('display_name', 'Unknown')}")
                return True
            else:
                print("✗ Authentication failed")
                print("  Run OAuth flow to get fresh access token")
                return False
        else:
            print("⚠️  No access token configured")
            print("  Run OAuth flow to authenticate")
            return False
            
    except ImportError:
        print("✗ TikTok API module not found")
        print("  Make sure src/tiktok_api.py exists")
        return False
    except Exception as e:
        print(f"✗ Error testing API: {e}")
        return False


def show_instructions():
    """Show usage instructions"""
    print()
    print("=" * 70)
    print("📖 How to Use TikTok API with Your Bot")
    print("=" * 70)
    print()
    print("1. Configure credentials:")
    print("   python tiktok_setup.py")
    print()
    print("2. Authenticate with OAuth:")
    print("   python tiktok_oauth_flow.py")
    print()
    print("3. Use in your bot:")
    print("   from src.video_watcher_agent import VideoWatcherAgent")
    print("   agent = VideoWatcherAgent(use_real_api=True)")
    print("   agent.heart_video_with_api('1', 'tiktok_video_id')")
    print("   agent.heart_video_multi_with_api('1', 'tiktok_video_id', bot_count=50)")
    print()
    print("4. Run interactive bot:")
    print("   python video_watcher.py")
    print()


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == "test":
        test_api_connection()
    else:
        get_tiktok_credentials()
        show_instructions()
